env: prod

server:
  dev:
    app: controller.handler:cinema_backend
    host: 127.0.0.1
    port: 8000
    reload: true

  test:
    app: controller.handler:cinema_backend
    host: 127.0.0.1
    port: 8001
    reload: false

  prod:
    app: controller.handler:cinema_backend
    host: 0.0.0.0
    port: 8000
    reload: false

logging:
  dev:
    level: DEBUG
    console: true
    file: logs/dev.log

  test:
    level: WARNING
    console: true
    file: logs/test.log

  prod:
    level: INFO
    console: true
    file: logs/app.log